---
root_group: root
nginx_conf_path: /etc/nginx/conf.d
nginx_conf_file_path: /etc/nginx/nginx.conf
nginx_mime_file_path: /etc/nginx/mime.types
nginx_pidfile: /run/nginx.pid
nginx_vhost_path: /etc/nginx/sites-enabled
nginx_default_vhost_path: /etc/nginx/sites-enabled/default
__nginx_user: "www-data"

nginx_vhosts:
  - listen: "80"
    server_name: "ansible.com"
    state: "present"
    template: "{{ nginx_vhost_template }}"
    filename: "ansible.com"
    extra_parameters: |
      location / {
        proxy_pass http://app:3000;
      }

