---
root_group: root
nginx_conf_path: /etc/nginx/conf.d
nginx_conf_file_path: /etc/nginx/nginx.conf
nginx_mime_file_path: /etc/nginx/mime.types
nginx_pidfile: /run/nginx.pid
nginx_vhost_path: /etc/nginx/sites-enabled
nginx_default_vhost_path: /etc/nginx/sites-enabled/default
__nginx_user: "www-data"

nginx_vhosts:
  - listen: "80"
    server_name: "ansible.com"
    state: "present"
    template: "{{ nginx_vhost_template }}"
    filename: "ansible.com"
    extra_parameters: |
      location / {
        proxy_pass http://app;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
      }

nginx_upstreams:
  - name: app
    strategy: "least_conn" # "least_conn", etc.
    servers: {
      "app:3000 max_fails=3 fall_timeout=30s"
    }

