version: "2"
settings:
  conductor:
    base: 'ubuntu:xenial'
  project_name: hello-world
  roles_path:
    - /vagrant/provisioning/roles/provision
services: 
  # Add your containers here, specifying the base image you want to build from.
  # To use this example, uncomment it and delete the curly braces after services key.
  # You may need to run `docker pull ubuntu:trusty` for this to work.
  nginx:
    image: nginx
    volumes:
     - ../../app:/vagrant
    ports:
      - "80:80"
      - "3000:3000"
    networks:
     - sd-net
  
  app:
    image: node:latest
    volumes:
      - ../../app:/vagrant
      - /app/node_modules
    expose:
      - "3000"
    ports:
      - "3001:3001"
    networks:
      - sd-net
  
  mongo:
    image: mongo
    volumes:
      - mongodata:/data/db
    ports:
      - "27017:27017"
    networks:
      - sd-net

networks:
  sd-net:
    driver: "bridge"

volumes:
  mongodata:
    driver: "local"
