version: '2'
services:
  nginx:
    image: nginx
    volumes:
     - ../../app:/vagrant
    networks:
     - sd-net
  
  app:
    image: node:latest
    volumes:
      - ../../app:/vagrant
      - /app/new-app/node_modules
    networks:
      - sd-net
  
  mongo:
    image: mongo
    volumes:
      - mongodata:/data/db
    networks:
      - sd-net
    
networks:
  sd-net:
    driver: "bridge"

volumes:
  mongodata:
    driver: "local"