---

########################################
## Ansible Playbook for installing Nginx
########################################
- hosts: control
  become: true 
  tasks:
    - name: ensure repository key is installed
      apt_key:
        id: "58118E89F3A912897C070ADBF76221572C52609D"
        keyserver: "hkp://p80.pool.sks-keyservers.net:80"
        state: present

    - name: ensure docker registry is available
      apt_repository: 
        repo: deb https://apt.dockerproject.org/repo ubuntu-xenial main
        state: present
    
    - name: apt update
      apt: 
        update_cache: yes
    
    - name: ensure docker and dependencies are installed
      apt: 
        name: docker-engine 
        state: present

    - service: name=docker state=restarted

    - name: users | adding docker users (for use without sudo)
      user:
        name: "vagrant"
        append: yes
        groups: "{{ item }}"
      become: true
      with_items:
        - docker
        - dialout

    - name: Installing packages
      apt: 
        name: "{{ item }}"
        state: present
      with_items:
        - python-setuptools
        - htop

    - name: Installing dependencies
      easy_install:
        name: pip

    - name: Installing docker compose
      pip:
        name: "{{ item }}"
        state: present
      with_items:
        - ansible-container[docker]

    
    # - name: Build with Ansible Container
    #   command: ansible-container --debug build
    #   args:
    #     chdir: /vagrant/provisioning/container

    # - name: Run Ansible Container
    #   command: ansible-container run
    #   args:
    #     chdir: /vagrant/provisioning/container

    - name: Delete Aliases file
      file:
        state: absent
        path:  /home/vagrant/.bash_aliases
    
    - name: Bash aliases | Add aliases
      lineinfile:
        path:  /home/vagrant/.bash_aliases
        group: vagrant
        owner: vagrant
        mode: 0644
        create: yes
        line: "alias {{ item.alias }}='{{ item.command }}'"
        state: present
        insertafter: EOF
      with_items: 
        - { alias: 'app', command: 'docker run --rm -v $(pwd):/var -w /var hello-world-app' }
        - { alias: 'nginx', command: 'docker run --rm -v $(pwd):/var -w /var nginx' }
        - { alias: 'npm', command: 'app npm' }
        - { alias: 'npx', command: 'app npx' }
        - { alias: 'node', command: 'app node' }
        - { alias: 'yarn', command: 'app yarn' }
      
    - name: Bash profiles | Add profiles
      lineinfile:
        path:  /home/vagrant/.profile
        group: vagrant
        owner: vagrant
        mode: 0644
        create: yes
        line: "{{ item }}"
        state: present
        insertafter: EOF
      with_items: 
        - 'cd /vagrant'
        
    # - name: Create new React App
    #   command: docker run --rm -v /vagrant:/var -w /var hello-world-app npx create-react-app app
    #   args:
    #     chdir: /vagrant
    #     creates: /vagrant/app/package.json