---

########################################
## Ansible Playbook for installing Nginx
########################################
- hosts: control
  become: true 
  tasks:
    - name: ensure repository key is installed
      apt_key:
        id: "58118E89F3A912897C070ADBF76221572C52609D"
        keyserver: "hkp://p80.pool.sks-keyservers.net:80"
        state: present

    - name: ensure docker registry is available
      apt_repository: 
        repo: deb https://apt.dockerproject.org/repo ubuntu-xenial main
        state: present
    
    - name: apt update
      apt: 
        update_cache: yes
    
    - name: ensure docker and dependencies are installed
      apt: 
        name: docker-engine 
        state: present

    - service: name=docker state=restarted

    - name: users | adding docker users (for use without sudo)
      user:
        name: "vagrant"
        append: yes
        groups: docker
      become: true

    - name: Installing packages
      apt: 
        name: "{{ item }}"
        state: present
      with_items:
        - python-setuptools
        - htop

    - name: Installing dependencies
      easy_install:
        name: pip

    - name: Installing docker compose
      pip:
        name: "{{ item }}"
        state: present
      with_items:
        - ansible-container[docker]
    
    # - name: Build with Ansible Container
    #   command: ansible-container build
    #   args:
    #     chdir: /vagrant/provisioning/container

    # - name: Run Ansible Container
    #   command: ansible-container run
    #   args:
    #     chdir: /vagrant/provisioning/container

